### ISSUE TITLE
KeyError: 'args' when loading pretrained model in translation step

### ISSUE THREAD

**Issue by DEVILENMO** [facebookresearch/ssvp_slt#2]
Body:

Hello,

I've encountered an issue while following the training process for SSVP-SLT. After completing the Pretraining_clip step and moving to the translation phase, I'm encountering an error when trying to load the pretrained model.

Steps to Reproduce:

Completed the Pretraining_clip step as per instructions.
Attempted to load the pretrained model in the translation step.

Error Message:
```
KeyError: 'args'
```

Full Traceback:
```Python
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/site-packages/submitit/core/submission.py", line 69, in process_job
    raise error
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/a/anaconda3/envs/ssvp_slt/lib/python3.10/site-packages/stopes/core/stopes_module.py", line 97, in __call__
    res = self.run(iteration_value=iteration_value, iteration_index=iteration_index)
  File "/home/a/b/ssvp_slt/translation/launch_feature_extraction.py", line 218, in run
    model = self.load_model(device=device)
  File "/home/a/b/ssvp_slt/translation/launch_feature_extraction.py", line 148, in load_model
    model = SignHiera.from_clip_model(
  File "/home/a/b/ssvp_slt/src/ssvp_slt/modeling/sign_hiera.py", line 607, in from_clip_model
    args = checkpoint["args"]
KeyError: 'args'
```

Checkpoint Contents:
I've inspected the checkpoint file, and it contains the following keys:
```
Checkpoint keys:
- clip
- optimizer
- scaler
- gradnorm
- optimizer_gradnorm
- scaler_gradnorm
- cfg
- epoch
```

As you can see, there is no 'args' key in the checkpoint, which is causing the KeyError.

Expected Behavior:
The pretrained model should load successfully for use in the translation step.

Actual Behavior:
The code is attempting to access a non-existent 'args' key in the checkpoint, resulting in a KeyError.

Questions:

Is the 'args' key supposed to be present in the checkpoint after the Pretraining_clip step?
If not, how should the from_clip_model method in sign_hiera.py be modified to handle checkpoints without the 'args' key?
The 'cfg' key in the checkpoint doesn't contain the information that the code is expecting to find in 'args'.
Any guidance on how to resolve this issue would be greatly appreciated. Thank you for your time and assistance.

**Comment by xplip** [comment]
Hi, thanks for raising this issue! This seems to be a bug that resulted from refactoring, and I've now created a pull request that should fix it. Please reach out if anything else is unclear

**Comment by DEVILENMO** [comment]
> Hi, thanks for raising this issue! This seems to be a bug that resulted from refactoring, and I've now created a pull request that should fix it. Please reach out if anything else is unclear

Thank you for addressing the issue I reported earlier. Your fix has been very helpful. However, I've now encountered another problem while trying to train the translation network as per the instructions in the translation.md file.

When I run the following command:

```bash
python run_translation.py \
    --config-name slt_t5 \
    --multirun \
    run=local \
    hydra.sweep.dir=sweep_t5 \
    data.train_data_dirs=../exp_feature_output/phoenix  \
    data.val_data_dir=../exp_feature_output/phoenix \
    optim.train_batch_size=4 \
    optim.gradient_accumulation_steps=1 \
    common.eval_steps=500 \
    common.seed=1,2,3,4,5
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/a/b/ssvp_slt/translation/run_translation.py", line 21, in <module>
    from main_translation import main as translate
  File "/home/a/b/ssvp_slt/translation/main_translation.py", line 15, in <module>
    from engine_translation import evaluate, evaluate_full, train_one_epoch
  File "/home/a/b/ssvp_slt/translation/engine_translation.py", line 26, in <module>
    from ssvp_slt.modeling.fairseq_model import FairseqTokenizer
  File "/home/a/b/ssvp_slt/src/ssvp_slt/modeling/fairseq_model.py", line 21, in <module>
    from fairseq.models.sign_language import Sign2TextTransformerModel
ModuleNotFoundError: No module named 'fairseq.models.sign_language'
```
I've already extracted the features as required, but the training process fails to start due to this error. Could you please advise on how to resolve this issue? Is there a specific version of fairseq that I should be using, or perhaps some additional installation steps that I might have missed?

Thank you for your continued support.

**Comment by xplip** [comment]
Have you installed the fork of fairseq in the root folder of this repo (https://github.com/facebookresearch/ssvp_slt/tree/main/fairseq-sl)? If not, then doing so should resolve that error. Some notes:
- You might need to downgrade pip to 24.0 (related to https://github.com/facebookresearch/fairseq/issues/5511) and you'll need GCC 9+ to install this fairseq version
- When installing that fairseq on top of an existing SSVP-SLT installation, there might be errors thrown by pip about conflicting dependencies, relating to the versions of hydra & omegaconf. I would therefore recommend to first install fairseq (which installs older versions of hydra & omegaconf), and then the SSVP-SLT package, which will come with newer versions. Generally, following the order of steps in https://github.com/facebookresearch/ssvp_slt/blob/main/INSTALL.md#3-pip-installs should work.

**Comment by DEVILENMO** [comment]
> Have you installed the fork of fairseq in the root folder of this repo (https://github.com/facebookresearch/ssvp_slt/tree/main/fairseq-sl)? If not, then doing so should resolve that error. Some notes:
> 
> * You might need to downgrade pip to 24.0 (related to ["ERROR: Cannot install fairseq and fairseq==0.12.2 because these package versions have conflicting dependencies." fairseq#5511](https://github.com/facebookresearch/fairseq/issues/5511)) and you'll need GCC 9+ to install this fairseq version
> * When installing that fairseq on top of an existing SSVP-SLT installation, there might be errors thrown by pip about conflicting dependencies, relating to the versions of hydra & omegaconf. I would therefore recommend to first install fairseq (which installs older versions of hydra & omegaconf), and then the SSVP-SLT package, which will come with newer versions. Generally, following the order of steps in https://github.com/facebookresearch/ssvp_slt/blob/main/INSTALL.md#3-pip-installs should work.

Thank you for your support， I’will try later.
